### ISSUE TITLE
Document backtrace line link support

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-docs#288]
Document how to set up backtrace links to a system of choice:

- [x] Have deploy markers set up
- [x] Configure a backtrace line URL, or;
- [x] Link your organization with our GitHub app

Related: https://github.com/appsignal/appsignal-docs/issues/179

## TODO

- [ ] Create the GitHub specific page #179 
- [x] Create a page in the application section for this feature with all of its requirements #295
