### ISSUE TITLE
Document Elixir functionality

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-docs#69]
- [x] Update configuration pages
- [x] Debugging AppSignal for Elixir #74 
- [x] Installation page. Mention manual setup but prefer install task
- [x] Integrating AppSignal in Elixir page, PR #88
  - See demo task for simple implementation
- [x] Custom instrumentation page updates #90 
  - See demo task for simple implementation
- [x] Custom metrics
- [x] Tagging PR: #89
- [x] Exception handling page PR: #87
  - `Appsignal.send_error`
  - like http://docs.appsignal.com/ruby/instrumentation/exception-handling.html
- [x] Update type definitions, as reported in https://github.com/appsignal/appsignal-docs/pull/85 PR: #86 
- [x] Things from: https://github.com/appsignal/appsignal-docs/issues/79

Make sure to update the docs in the Elixir page itself https://github.com/appsignal/appsignal-elixir so they don't contradict each other
